# Generated by Django 2.0.3 on 2018-05-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='doc',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
