# Generated by Django 2.0.3 on 2018-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20180504_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
