# Generated by Django 2.0.3 on 2018-05-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20180507_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
