# Generated by Django 2.0.3 on 2018-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180413_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='questions',
        ),
        migrations.AddField(
            model_name='job',
            name='question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
