# Generated by Django 2.0.3 on 2018-04-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180417_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='question',
        ),
    ]
